name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1", "8.2", "8.3"]
        laravel: ["^9.0", "^10.0"]
        dependencies:
            - "lowest"
            - "highest"
        exclude:
          - php: "8.0"
            laravel: "^10.0"
            dependencies: "lowest"
          - php: "8.0"
            laravel: "^10.0"
            dependencies: "highest"

    name: "PHP${{ matrix.php }} - Laravel${{ matrix.laravel }} ${{ matrix.dependencies == 'highest' && '↑' || '↓' }}"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "dom, curl, libxml, mbstring, zip, fileinfo"
          tools: "composer:v2"
          coverage: "none"

      - name: "Check Composer configuration"
        run: "composer validate --strict"

      - name: "Install lowest dependencies from composer.json"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --with='laravel/framework:${{ matrix.laravel }}' --no-interaction --no-progress --prefer-lowest"

      - name: "Install highest dependencies from composer.json"
        if: "matrix.dependencies == 'highest'"
        run: "composer update --with='laravel/framework:${{ matrix.laravel }}' --no-interaction --no-progress"

      - name: "Check PSR-4 mapping"
        run: "composer dump-autoload --optimize --strict-psr"

      - name: "Execute unit tests"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=test-report.xml --testdox"
